spring:
  application:
    name: vedu-backend

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    sql-migration-suffixes: .pgsql

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: 900000
  refresh-token:
    expiration: 1209600000

crypto:
  email:
    encryption-key: ${EMAIL_ENCRYPTION_KEY}
    iv-key: ${EMAIL_IV_KEY}
